In [56]:
# Importando bibliotecas necessárias para a construção de grafos
import netpixi
from netpixi.integration.gt import *
import pandas as pd
import numpy as np
import csv
import ast

In [57]:
df = pd.read_csv('./Video_Games_Sales_as_at_22_Dec_2016.csv')
df.dropna(subset=['Publisher'], inplace=True)
df

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8.0,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8.0,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16715,LMA Manager 2007,X360,2006.0,Sports,Codemasters,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16716,Haitaka no Psychedelica,PSV,2016.0,Adventure,Idea Factory,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16717,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16718,Winning Post 8 2016,PSV,2016.0,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
df.groupby('Genre')['Name'].count().sort_values(ascending=False)

Genre
Action          3364
Sports          2345
Misc            1723
Role-Playing    1499
Shooter         1321
Adventure       1299
Racing          1248
Platform         887
Simulation       870
Fighting         847
Strategy         680
Puzzle           580
Name: Name, dtype: int64

In [59]:
df_grouped_Genre = df.groupby(['Genre']).agg({'Global_Sales': np.mean})
df_grouped_Genre.sort_values('Global_Sales', ascending=False)

              Global_Sales
Genre
Platform          0.933033
Shooter           0.797048
Role-Playing      0.623316
Racing            0.584046
Sports            0.567343
Fighting          0.524522
Action            0.518564
Misc              0.461619
Simulation        0.448483
Puzzle            0.419000
Strategy          0.256191
Adventure         0.182771

In [60]:
sports_mean_sales = df_grouped_Genre.loc['Sports']['Global_Sales']
action_mean_sales = df_grouped_Genre.loc['Action']['Global_Sales'] 
rpg_mean_sales = df_grouped_Genre.loc['Role-Playing']['Global_Sales']

In [61]:
def segregate_genre_to_list(df, genre, df_list, threshold=None):
    seg_df = df[df['Genre'] == genre]
    if threshold:
        seg_df = seg_df[seg_df['Global_Sales'] > threshold]
    df_list.append(seg_df)

In [62]:
sorted_years = df['Year_of_Release'].unique()
sorted_years.sort()
print(sorted_years)

[1980. 1981. 1982. 1983. 1984. 1985. 1986. 1987. 1988. 1989. 1990. 1991.
 1992. 1993. 1994. 1995. 1996. 1997. 1998. 1999. 2000. 2001. 2002. 2003.
 2004. 2005. 2006. 2007. 2008. 2009. 2010. 2011. 2012. 2013. 2014. 2015.
 2016. 2017. 2020.   nan]

In [63]:
df_list = []
sport_df_list = []
action_df_list = []
rpg_df_list = []
for i in range(0, len(sorted_years), 12):
    df_list.append(df[df['Year_of_Release'].isin(sorted_years[i:i+5])])

In [64]:
df_list[0]

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
9,Duck Hunt,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31,NaN,NaN,NaN,NaN,NaN,NaN
89,Pac-Man,2600,1982.0,Puzzle,Atari,7.28,0.45,0.00,0.08,7.81,NaN,NaN,NaN,NaN,NaN,NaN
240,Pitfall!,2600,1981.0,Platform,Activision,4.21,0.24,0.00,0.05,4.50,NaN,NaN,NaN,NaN,NaN,NaN
262,Asteroids,2600,1980.0,Shooter,Atari,4.00,0.26,0.00,0.05,4.31,NaN,NaN,NaN,NaN,NaN,NaN
281,Excitebike,NES,1984.0,Racing,Nintendo,2.04,0.48,1.57,0.07,4.16,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8458,Death Trap,2600,1982.0,Action,Avalon Interactive,0.15,0.01,0.00,0.00,0.17,NaN,NaN,NaN,NaN,NaN,NaN
8459,Armor Ambush,2600,1981.0,Action,Mattel Interactive,0.15,0.01,0.00,0.00,0.17,NaN,NaN,NaN,NaN,NaN,NaN
8740,Pressure Cooker,2600,1982.0,Action,Activision,0.14,0.01,0.00,0.00,0.15,NaN,NaN,NaN,NaN,NaN,NaN
9096,Krull,2600,1982.0,Action,Atari,0.13,0.01,0.00,0.00,0.14,NaN,NaN,NaN,NaN,NaN,NaN
9488,RealSports Volleyball,2600,1981.0,Sports,Atari,0.12,0.01,0.00,0.00,0.13,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
publisher_platforms = []
for db in df_list:
    publisher_platforms.append(db.groupby('Platform')['Publisher'].unique().to_dict())

In [66]:
publishers = df["Publisher"].unique()
publishers

array(['Nintendo', 'Microsoft Game Studios', 'Take-Two Interactive',
       'Sony Computer Entertainment', 'Activision', 'Ubisoft',
       'Bethesda Softworks', 'Electronic Arts', 'Sega', 'SquareSoft',
       'Atari', '505 Games', 'Capcom', 'GT Interactive',
       'Konami Digital Entertainment', 'Square Enix',
       'Sony Computer Entertainment Europe', 'Virgin Interactive',
       'LucasArts', 'Warner Bros. Interactive Entertainment',
       'Universal Interactive', 'Eidos Interactive', 'RedOctane',
       'Vivendi Games', 'Enix Corporation', 'Namco Bandai Games',
       'Palcom', 'Hasbro Interactive', 'THQ', 'Fox Interactive',
       'Acclaim Entertainment', 'MTV Games', 'Disney Interactive Studios',
       'Codemasters', 'Majesco Entertainment', 'Red Orb', 'Level 5',
       'Arena Entertainment', 'Midway Games', 'JVC', 'Deep Silver',
       'NCSoft', '989 Studios', 'UEP Systems', 'Parker Bros.', 'Maxis',
       'Imagic', 'Tecmo Koei', 'ASCII Entertainment', 'Valve Software',
       'Mindscape', 'Infogrames', 'Unknown', 'Square', 'Valve',
       'Banpresto', 'Hello Games', 'D3Publisher', 'Activision Value',
       'Oxygen Interactive', 'Red Storm Entertainment', 'Video System',
       'Global Star', 'Gotham Games', 'Westwood Studios', 'GungHo',
       'Crave Entertainment', 'Hudson Soft', 'Coleco',
       'Rising Star Games', 'TDK Mediactive', 'ASC Games', 'Accolade',
       'Zoo Games', 'Sony Oznline Entertainment', '3DO', 'Natsume', 'RTL',
       'Alchemist', 'Black Label Games', 'SouthPeak Games',
       'Focus Home Interactive', 'Ocean', 'Zoo Digital Publishing',
       'Psygnosis', 'City Interactive', 'Empire Interactive', 'Success',
       'Compile', 'Russel', 'Atlus', 'Mastertronic',
       'Slightly Mad Studios', 'Taito', 'Agetec', 'Microprose', 'Play It',
       'GSP', 'Tomy Corporation', 'Sammy Corporation', 'Koch Media',
       'Game Factory', 'Titus', 'Marvelous Entertainment', 'Genki',
       'Mojang', 'CTO SpA', 'TalonSoft', 'Crystal Dynamics',
       'Square Enix ', 'mixi, Inc', 'Pinnacle', 'SCi', 'Quelle',
       'Rage Software', 'Ubisoft Annecy', 'Interplay', 'Scholastic Inc.',
       'Mystique', 'ChunSoft', 'Square EA',
       '20th Century Fox Video Games', 'Hudson Entertainment',
       'Men-A-Vision', 'Nobilis', 'Avanquest Software',
       'Big Ben Interactive', 'Nordic Games', 'Touchstone', 'Spike',
       'Nippon Ichi Software', 'Sony Computer Entertainment America',
       'Jester Interactive', 'LEGO Media', 'Quest', 'Illusion Softworks',
       'Tigervision', 'Rocket Company', 'Metro 3D', 'Mattel Interactive',
       'IE Institute', 'Funbox Media', 'Sony Online Entertainment',
       'Rondomedia', 'Universal Gamex', 'Ghostlight',
       'Wizard Video Games', 'BMG Interactive Entertainment', 'PQube',
       'Trion Worlds', 'Xseed Games', 'Laguna', 'Takara',
       'Ignition Entertainment', 'Kadokawa Shoten', 'Enterbrain',
       'Imagineer', 'CPG Products', 'System 3 Arcade Software',
       'Aruze Corp', 'Destineer', 'Gamebridge',
       'Midas Interactive Entertainment', 'Jaleco', 'Answer Software',
       'Pack In Soft', 'XS Games', 'Rebellion', 'Ultravision',
       'Harmonix Music Systems', 'Activision Blizzard', 'Xplosiv',
       'Wanadoo', 'Telltale Games', 'NovaLogic', 'Epoch',
       'BAM! Entertainment', 'GameMill Entertainment',
       'Knowledge Adventure', 'Tetris Online', 'Mastiff', 'ESP', 'TYO',
       'Telegames', 'Mud Duck Productions', 'Screenlife', 'Pioneer LDC',
       'Magical Company', 'Kemco', 'Mentor Interactive',
       'Human Entertainment', 'Data Age', 'Electronic Arts Victor',
       'Jack of All Games', 'Avanquest', 'Black Bean Games', '989 Sports',
       'Takara Tomy', 'Media Rings', 'Elf', 'Starfish', 'Zushi Games',
       'Jorudan', 'Destination Software, Inc', 'New',
       'Brash Entertainment', 'Kalypso Media', 'ITT Family Games',
       'Ackkstudios', 'PopCap Games', 'Starpath Corp.', 'BPS',
       'Gathering of Developers', 'NewKidCo', 'Marvelous Interactive',
       'Storm City Games', 'CokeM Interactive', 'P2 Games',
       'CBS Electronics', 'Home Entertainment Suppliers', 'Magix',
       'Arc System Works', 'Angel Studios', 'Wargaming.net', 'Playmates',
       'SNK Playmore', 'Hamster Corporation', 'From Software',
       'Nippon Columbia', 'Nichibutsu', 'Conspiracy Entertainment',
       'Hect', 'Mumbo Jumbo', 'DTP Entertainment',
       'Pacific Century Cyber Works', 'Indie Games', 'Liquid Games',
       'NEC', 'Axela', 'ArtDink', 'Sunsoft', 'Little Orbit', 'FuRyu',
       'Gust', 'SNK', 'NEC Interchannel', 'Nihon Falcom Corporation',
       'Xing Entertainment', 'ValuSoft', 'Victor Interactive',
       'American Softworks', 'Falcom Corporation', 'Detn8 Games', 'Bomb',
       'Nordcurrent', 'Milestone S.r.l.', 'AQ Interactive', 'Sears',
       'Seta Corporation', 'On Demand', 'CCP', 'NCS',
       'Rebellion Developments', 'Agatsuma Entertainment',
       'Gremlin Interactive Ltd', 'Aspyr', 'Compile Heart',
       'Culture Brain', 'Mad Catz', 'Shogakukan', 'Merscom LLC',
       'JoWood Productions', 'Nippon Telenet', 'TDK Core',
       'Kadokawa Games', 'SSI', 'Foreign Media Games', 'Core Design Ltd.',
       'bitComposer Games', 'Astragon', 'Asylum Entertainment',
       'Performance Designed Products', 'UFO Interactive',
       'Essential Games', 'Adeline Software', 'Funcom', 'PlayV',
       'Panther Software', 'Blast! Entertainment Ltd',
       'Playlogic Game Factory', 'DSI Games', 'Avalon Interactive',
       'Game Life', 'Popcorn Arcade', 'Aques', 'System 3', 'Syscom',
       'Vir2L Studios', 'Vatical Entertainment', 'Neko Entertainment',
       'White Park Bay Software', 'Vic Tokai', 'Media Factory',
       'Daedalic', 'Game Arts', 'The Adventure Company', 'EA Games',
       'Acquire', 'Broccoli', 'General Entertainment',
       'Paradox Interactive', 'Yacht Club Games', 'Imadio',
       'Swing! Entertainment', 'Sony Music Entertainment', 'Aqua Plus',
       'Excalibur Publishing', 'Hip Interactive', 'Tripwire Interactive',
       'DreamCatcher Interactive', 'SCS Software', 'Havas Interactive',
       'Sting', 'Idea Factory', 'Telstar', 'U.S. Gold', 'Funsta',
       'DreamWorks Interactive', 'Slitherine Software', 'MTO', 'Graffiti',
       'Tru Blu Entertainment', 'DHM Interactive', 'Crytek', 'FunSoft',
       'Data Design Interactive', 'SPS', 'Moss', 'T&E Soft',
       'NDA Productions', 'Bigben Interactive', 'Data East',
       'Idea Factory International', 'Time Warner Interactive',
       'Gainax Network Systems', 'Daito', 'O3 Entertainment', 'O-Games',
       'Gameloft', 'Xicat Interactive', 'Simon & Schuster Interactive',
       'Valcon Games', 'PopTop Software', 'TOHO', 'PM Studios',
       'Bohemia Interactive', 'Reef Entertainment', '5pb',
       'HMH Interactive', 'inXile Entertainment', 'Cave', 'Microids',
       'Paon', 'CDV Software Entertainment', 'Micro Cabin', 'GameTek',
       'Benesse', 'Type-Moon', 'Enjoy Gaming ltd.', 'Asmik Corp',
       'Interplay Productions', 'Asmik Ace Entertainment', 'Image Epoch',
       'Phantom EFX', 'Evolved Games', 'responDESIGN',
       'Griffin International', 'Culture Publishers', 'Hackberry',
       'Hearty Robin', 'Nippon Amuse', 'Origin Systems', 'Seventh Chord',
       'Abylight', 'Mitsui', 'Insomniac Games', 'Flight-Plan',
       'Milestone', 'Glams', 'Aksys Games', 'Locus', 'Warp',
       'Irem Software Engineering', 'Myelin Media',
       'Global A Entertainment', 'Alternative Software', 'Mercury Games',
       'Sunrise Interactive', 'Elite', 'Evolution Games',
       'Daedalic Entertainment', 'Edia', 'Athena', 'Aria', 'Tivola',
       'Happinet', 'Tommo', 'Altron', 'Revolution Software',
       'Media Works', 'Fortyfive', 'Gamecock', 'Imax', '10TACLE Studios',
       'Groove Games', 'Pack-In-Video', 'Crimson Cow', 'iWin', 'Asgard',
       'Ecole', 'Yumedia', 'Ascaron Entertainment GmbH', 'HAL Laboratory',
       'Phenomedia', 'Grand Prix Games', 'DigiCube', 'Creative Core',
       'Kaga Create', 'WayForward Technologies', 'LSP Games',
       'ASCII Media Works', '1C Company', 'Coconuts Japan', 'Arika',
       'Marvel Entertainment', 'Ertain', 'Prototype', 'Phantagram',
       'The Learning Company', 'TechnoSoft', 'MLB.com', 'Vap', 'Misawa',
       'Yeti', 'Dusenberry Martin Racing', 'Navarre Corp', 'Pow',
       'MediaQuest', 'Team17 Software', 'Max Five', 'Tradewest',
       'Comfort', 'Milestone S.r.l', 'Pony Canyon', 'Riverhillsoft',
       'Summitsoft', 'Playmore', 'Kool Kizz', 'Monte Christo Multimedia',
       'TopWare Interactive', 'Legacy Interactive',
       'Cloud Imperium Games Corporation', 'Flashpoint Games',
       'CyberFront', 'Alawar Entertainment', 'Societa', 'Interchannel',
       'Experience Inc.', 'Sonnet', 'Virtual Play Games', 'Zenrin',
       'Iceberg Interactive', 'Ivolgamus', 'MC2 Entertainment', '2D Boy',
       'Games Workshop', 'Kando Games', 'Office Create',
       'Maximum Family Games', 'Fields', 'Gearbox Software',
       'Princess Soft', 'Extreme Entertainment Group', 'Big Fish Games',
       'Berkeley', 'Mamba Games', 'Fuji', 'FuRyu Corporation',
       'Her Interactive', 'imageepoch Inc.', 'Just Flight', 'Kamui',
       'ASK', 'Cygames', 'Introversion Software', '49Games', 'KSS',
       'dramatic create', 'TGL', 'KID', 'Quinrose', 'Sold Out', 'Encore',
       'G.Rev', 'Sunflowers', 'Headup Games', 'Sweets',
       'Kokopeli Digital Studios', 'id Software', 'Nexon', 'BushiRoad',
       'Devolver Digital', 'Number None', 'Tryfirst', 'GN Software',
       "Yuke's", 'Strategy First', 'Lexicon Entertainment',
       'Paon Corporation', 'Kids Station', 'Licensed 4U', 'GOA',
       '7G//AMES', 'King Records', 'Minato Station',
       'Graphsim Entertainment', 'Easy Interactive', 'Gaga',
       'Yamasa Entertainment', 'Plenty', 'Views', 'Blue Byte', 'fonfun',
       'NetRevo', 'Epic Games', 'Quintet', 'Focus Multimedia',
       'Phoenix Games', 'Marvelous Games', 'Dorart', 'Codemasters Online',
       'Stainless Games', 'Aerosoft', 'Imageworks', 'Karin Entertainment',
       'Technos Japan Corporation', 'Masque Publishing', 'Gakken',
       'New World Computing', 'Mirai Shounen', 'Datam Polystar', 'HuneX',
       'Visco', 'Saurus', 'Revolution (Japan)', 'Giza10', 'Alvion',
       'Giga', 'Mycom', 'Warashi', 'System Soft', 'RED Entertainment',
       'Lighthouse Interactive', 'Michaelsoft', 'Media Entertainment',
       'Genterprise', 'Interworks Unlimited, Inc.', 'Inti Creates',
       'Boost On', 'EON Digital Entertainment', 'Nitroplus', 'Naxat Soft',
       'Piacci', 'Paradox Development', 'Otomate',
       'Ascaron Entertainment', 'Ongakukan', 'Commseed',
       'UIG Entertainment', 'Takuyo', 'Interchannel-Holon',
       'Red Flagship'], dtype=object)

In [79]:
df_list[1]

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN
45,Super Mario 64,N64,1996.0,Platform,Nintendo,6.91,2.85,1.91,0.23,11.89,NaN,NaN,NaN,NaN,NaN,NaN
50,Super Mario Land 2: 6 Golden Coins,GB,1992.0,Adventure,Nintendo,6.16,2.04,2.69,0.29,11.18,NaN,NaN,NaN,NaN,NaN,NaN
56,Super Mario All-Stars,SNES,1993.0,Platform,Nintendo,5.99,2.15,2.12,0.29,10.55,NaN,NaN,NaN,NaN,NaN,NaN
63,Mario Kart 64,N64,1996.0,Racing,Nintendo,5.55,1.94,2.23,0.15,9.87,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15855,Discworld II: Mortality Bytes!,PS,1996.0,Adventure,Psygnosis,0.01,0.01,0.00,0.00,0.02,NaN,NaN,NaN,NaN,NaN,NaN
16209,Rock N' Roll Racing,SNES,1993.0,Racing,Interplay,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16329,Victory Spike,PS,1996.0,Sports,Imagineer,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16472,Meru Purana,PS,1996.0,Strategy,Gust,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16670,Psychic Detective,PS,1995.0,Adventure,Electronic Arts,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
action_graph = Graph(directed=False) # não-dirigido

for pub in publishers:
    action_graph.add_vertex(pub)

year = 0
# link every publisher to every other publisher by time period
for i in range(len(publishers)):
    for j in range(i+1, len(publishers)):
        for db in action_df_list:
            if publishers[i] in df_list[year]['Publisher'].values and publishers[j] in db['Publisher'].values:
                action_graph.add_edge(publishers[i], publishers[j])

In [69]:
print('número de vértices de g:', action_graph.num_edges())

número de vértices de g: 0

In [52]:
gt_save(action_graph, 'action_graph.net.gz')

In [53]:
g = gt_load('action_graph.net.gz')
g = gt_clean(g)
m = gt_draw.sfdp_layout(g)
gt_move(g, m)
gt_save(g, 'action_sfdp.net.gz')

In [55]:
r = netpixi.render('action_sfdp.net.gz', infinite=True);

In [47]:
rpg_graph = Graph(directed=False) # não-dirigido

for publisher in rpg_publishers:
    rpg_graph.add_vertex(publisher)

In [48]:
for platform_dict in publisher_platforms:
    for platform, publishers in platform_dict.items():
        for i in range(len(publishers)):
            if i != len(publishers)-1:
                next_vertex = i+1
                while(next_vertex < len(publishers)):
                    if(publishers[i] != publishers[next_vertex]):
                        try:
                            rpg_graph.add_edge(publishers[i], publishers[next_vertex])
                            #shared_pathogens.get_edge(publishers[i]-1, publishers[next_vertex]-1)['strength'] = 1
                        except ValueError:
                            continue
                            #shared_pathogens.get_edge(publishers[i]-1, publishers[next_vertex]-1)['strength'] += 1
                        finally:    
                            next_vertex += 1
                    else:
                        next_vertex += 1
                    
                    
print('número de arestas de g:', rpg_graph.num_edges())

número de arestas de g: 104

In [49]:
print('número de vértices de g:', rpg_graph.num_vertices())

número de vértices de g: 160

In [50]:
gt_save(rpg_graph, 'rpg_graph.net.gz')

In [51]:
g = gt_load('rpg_graph.net.gz')
m = gt_draw.sfdp_layout(g)
gt_move(g, m)
gt_save(g, 'rpg_sfdp.net.gz')

In [52]:
r = netpixi.render('rpg_sfdp.net.gz', infinite=True);

In [53]:
sports_graph = Graph(directed=False) # não-dirigido

for publisher in sports_publishers:
    sports_graph.add_vertex(publisher)

In [54]:
for platform_dict in publisher_platforms:
    for platform, publishers in platform_dict.items():
        for i in range(len(publishers)):
            if i != len(publishers)-1:
                next_vertex = i+1
                while(next_vertex < len(publishers)):
                    if(publishers[i] != publishers[next_vertex]):
                        try:
                            sports_graph.add_edge(publishers[i], publishers[next_vertex])
                            #shared_pathogens.get_edge(publishers[i]-1, publishers[next_vertex]-1)['strength'] = 1
                        except ValueError:
                            continue
                            #shared_pathogens.get_edge(publishers[i]-1, publishers[next_vertex]-1)['strength'] += 1
                        finally:    
                            next_vertex += 1
                    else:
                        next_vertex += 1
                    
                    
print('número de arestas de g:', sports_graph.num_edges())

número de arestas de g: 62

In [55]:
print('número de vértices de g:', sports_graph.num_vertices())

número de vértices de g: 164

In [56]:
gt_save(sports_graph, 'sports_graph.net.gz')

In [57]:
g = gt_load('sports_graph.net.gz')
m = gt_draw.sfdp_layout(g)
gt_move(g, m)
gt_save(g, 'sports_sfdp.net.gz')

In [58]:
r = netpixi.render('sports_sfdp.net.gz', infinite=True);